This exercise explores the data set of NYC Airbnb. Objective of this exercise is to use techniques from NumPy and Pandas to find insight in data. 

Data source - www.kaggle.com (https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data)

In [1]:
import numpy as np
import pandas as pd

In [2]:
nyc_airbnb_dataframe = pd.read_csv("DataSet/AB_NYC_2019.csv", sep=',')

nyc_airbnb_dataframe.describe()
#nyc_airbnb_dataframe.shape

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [3]:
nyc_airbnb_dataframe.columns.values
#nyc_airbnb_dataframe.tail(5)

array(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'], dtype=object)

In [4]:
del nyc_airbnb_dataframe['longitude']
del nyc_airbnb_dataframe['latitude']

nyc_airbnb_dataframe.shape

(48895, 14)

In [5]:
nyc_airbnb_dataframe.columns.values

array(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'room_type', 'price', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365'], dtype=object)

In [6]:
nyc_airbnb_dataframe.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,Private room,90,7,0,NaN,NaN,1,23

In [42]:
nyc_airbnb_dataframe.fillna({'reviews_per_month':0}, inplace=True)

#examine the change
nyc_airbnb_dataframe.reviews_per_month.isnull().sum()

0

In [39]:
print(nyc_airbnb_dataframe['calculated_host_listings_count'].min())
print(nyc_airbnb_dataframe['calculated_host_listings_count'].max())

print(nyc_airbnb_dataframe['reviews_per_month'].min())
print(nyc_airbnb_dataframe['reviews_per_month'].max())

1
327
0.0
58.5

In [47]:
most_visitors = ((nyc_airbnb_dataframe['calculated_host_listings_count'] > 100) & (nyc_airbnb_dataframe['minimum_nights'] < 30)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [44]:
nyc_airbnb_dataframe_x = nyc_airbnb_dataframe[most_visitors]

In [45]:
print(nyc_airbnb_dataframe_x.count())

id                                330
name                              330
host_id                           330
host_name                         330
neighbourhood_group               330
neighbourhood                     330
room_type                         330
price                             330
minimum_nights                    330
number_of_reviews                 330
last_review                       207
reviews_per_month                 330
calculated_host_listings_count    330
availability_365                  330
dtype: int64

In [29]:
nyc_airbnb_dataframe_x.head(50)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
9740,7491713,NYC Lavish Studio Apartment Steps from SoHo!,30283594,Kara,Manhattan,Financial District,Entire home/apt,169,30,3,2018-12-07,0.09,121,364
10075,7730160,Furnished NYC 1BR apt near Rockefeller Center!!!,30283594,Kara,Manhattan,Theater District,Entire home/apt,135,30,0,NaN,NaN,121,174
10335,7913426,LUX 1-Bedroom NYC Apartment Near Times Square!,30283594,Kara,Manhattan,Theater District,Entire home/apt,369,30,0,NaN,NaN,121,364
10398,7966358,NYC High End 2BR Midtown West Apt,30283594,Kara,Manhattan,Midtown,Entire home/apt,335,30,0,NaN,NaN,121,201
10490,8045421,NYC Chelsea Luxury 1BR Apt,30283594,Kara,Manhattan,Chelsea,Entire home/apt,129,30,3,2017-12-31,0.07,121,161
10530,8078896,Upscale Studio Apt in NYC'S Theatre District!,30283594,Kara,Manhattan,Theater District,Entire home/apt,203,30,0,NaN,NaN,121,365
10531,8081037,Lavish Studio with Great Amenities in FiDi,30283594,Kara,Manhattan,Financial District,Entire home/apt,189,30,4,2019-01-28,0.11,121,365
10643,8185845,1-Bedroom Upper East Side Apartment!,30283594,Kara,Manhattan,Upper East Side,Entire home/apt,249,30,2,2018-07-28,0.10,121,273
10803,8319784,~Lavish 1 Bedroom Upper East Side NYC Apt!,30283594,Kara,Manhattan,Upper East Side,Entire home/apt,249,30,1,2017-06-29,0.04,121,273
10804,8320129,Cozy Studio Apt Upper East Side Near Hospitals,30283594,Kara,Manhattan,Upper East Side,Entire home/apt,199,30,3,2018-04-22,0.11,121,365
11339,8810949,NYC Upscale Midtown East 3BR Apt,30283594,Kara,Manhattan,Midtown,Entire home/apt,1170,80,0,NaN,NaN,121,365
11488,8934119,Deluxe 1 Bedroom Chelsea NYC Apt!,30283594,Kara,Manhattan,Chelsea,Entire home/apt,269,30,0,NaN,NaN,121,337
11551,8988997,Beautiful Furnished 1 Bedroom NYC Apartment,30283594,Kara,Manhattan,Chelsea,Entire home/apt,129,30,0,NaN,NaN,121,164
11553,8989430,Furnished Luxury 1BR apt. in the heart of NYC!,30283594,Kara,Manhattan,Chelsea,Entire home/apt,136,30,0,NaN,NaN,121,349
11572,9003691,Luxury Studio Apartment in NYC'S Chelsea District,30283594,Kara,Manhattan,Chelsea,Entire home/apt,109,30,1,2016-10-31,0.03,121,184
11597,9025602,Luxury 1-Bedroom Financial District Apartment!,30283594,Kara,Manhattan,Financial District,Entire home/apt,229,30,0,NaN,NaN,121,184
11601,9026485,Luxury Studio Apt in NYC Financial District!,30283594,Kara,Manhattan,Financial District,Entire home/apt,169,30,2,2016-06-28,0.05,121,364
11621,9043722,Lavish 1BR in FiDi + city views,30283594,Kara,Manhattan,Financial District,Entire home/apt,239,30,2,2018-06-10,0.09,121,186
11693,9104505,Fully-Furnished 1-BR New York City Apt,30283594,Kara,Manhattan,Financial District,Entire home/apt,239,30,0,NaN,NaN,121,186
11695,9105223,Modernly Furnished 1 Bedroom Apt in FiDi,30283594,Kara,Manhattan,Financial District,Entire home/apt,239,30,0,NaN,NaN,121,186
11703,9107626,Luxurious studio apt. across from Battery Park!,30283594,Kara,Manhattan,Financial District,Entire home/apt,189,30,0,NaN,NaN,121,365
11745,9132807,Modernly Furnished Studio Apt in Midtown NYC,30283594,Kara,Manhattan,Midtown,Entire home/apt,139,30,0,NaN,NaN,121,360
11882,9250196,Furnished 1-BR near all NYC'S major attractions!,30283594,Kara,Manhattan,Theater District,Entire home/apt,230,30,0,NaN,NaN,121,363
11886,9251088,-Deluxe Furnished 1 Bedroom Apartment in Midtown,30283594,Kara,Manhattan,Theater District,Entire home/apt,239,30,0,NaN,NaN,121,363
12871,9806799,#Beautifully furnished 2 BR apt. near Central ...,30283594,Kara,Manhattan,Hell's Kitchen,Entire home/apt,369,30,0,NaN,NaN,121,331
12974,9855028,Upscale 1 Bedroom Midtown West NYC Apartment,30283594,Kara,Manhattan,Midtown,Entire home/apt,239,30,0,NaN,NaN,121,351
12976,9855273,Modern 1 bedroom apt. near Columbus Circle!,30283594,Kara,Manhattan,Hell's Kitchen,Entire home/apt,279,30,0,NaN,NaN,121,352
12986,9858642,NYC Midtown West 2-BR Apt near Theater District!,30283594,Kara,Manhattan,Midtown,Entire home/apt,369,30,1,2016-01-20,0.02,121,345
12990,9860190,Deluxe Furnished 1-Bedroom Midtown West Apartment,30283594,Kara,Manhattan,Theater District,Entire home/apt,239,30,0,NaN,NaN,121,363
12992,9860670,Deluxe Furnished 1-BR NYC apt. near Central Park!,30283594,Kara,Manhattan,Theater District,Entire home/apt,239,30,0,NaN,NaN,121,363
12993,9860948,Modern 1 bedroom apt. near Grand Central Stat...,30283594,Kara,Manhattan,Theater District,Entire home/apt,239,30,0,NaN,NaN,121,363
12994,9861196,Luxury 1-Bedroom Apartment in Midtown Gym+Pool,30283594,Kara,Manhattan,Theater District,Entire home/apt,239,30,1,2018-04-28,0.07,121,363
13021,9874710,Lux 1BR in the heart of NYC Theater district!,30283594,Kara,Manhattan,Theater District,Entire home/apt,139,30,1,2017-05-17,0.04,121,306
13031,9879556,**Luxury 1 Bedroom Upper East Side NYC Apt,30283594,Kara,Manhattan,Upper East Side,Entire home/apt,249,30,1,2018-01-25,0.06,121,273
13032,9879796,Modern 2 Bedroom by Memorial Sloan Kettering!,30283594,Kara,Manhattan,Upper East Side,Entire home/apt,249,30,0,NaN,NaN,121,272
13033,9880049,Furnished 1BR apt. near Empire State Building!,30283594,Kara,Manhattan,Midtown,Entire home/apt,239,30,0,NaN,NaN,121,352
13036,9880495,NYC Midtown West Luxury 1 bedroom apartment!,30283594,Kara,Manhattan,Midtown,Entire home/apt,239,30,0,NaN,NaN,121,351
13038,9880673,Lavish 1BR apt. near Madison Square Park!,30283594,Kara,Manhattan,Hell's Kitchen,Entire home/apt,239,30,0,NaN,NaN,121,352
13039,9880827,NYC luxury 1 BR apt near the Chrysler Building!,30283594,Kara,Manhattan,Midtown,Entire home/apt,239,30,0,NaN,NaN,121,352
13043,9881685,Upscale and spacious 2bed/2bath Midtown West apt.,30283594,Kara,Manhattan,Midtown,Entire home/apt,190,30,1,2017-04-30,0.04,121,286
13048,9882440,"Spectacular, high-end 2BR apt close to Bryant ...",30283594,Kara,Manhattan,Hell's Kitchen,Entire home/apt,369,30,3,2019-01-10,0.07,121,345
13154,9935992,Lux Studio Apt in Downtown NYC - Gym included!,30283594,Kara,Manhattan,Financial District,Entire home/apt,169,30,2,2017-11-17,0.06,121,364
13160,9937547,Upscale 2-Bedroom Upper Eastside Apt,30283594,Kara,Manhattan,Upper East Side,Entire home/apt,369,30,0,NaN,NaN,121,297
14228,11007370,~Lux 2-Bedroom NYC Apt near Times Square,30283594,Kara,Manhattan,Theater District,Entire home/apt,369,30,0,NaN,NaN,121,148
14935,11866751,Views of the Hudson NYC Apt.!!,30283594,Kara,Manhattan,Hell's Kitchen,Entire home/apt,239,30,2,2017-04-03,0.07,121,365
14946,11881208,Lavish Studio Apt in Midtown West NYC!,30283594,Kara,Manhattan,Hell's Kitchen,Entire home/apt,199,30,0,NaN,NaN,121,365
15040,12000676,~Luxury 1 bedroom apt. near Columbus Circle,30283594,Kara,Manhattan,Midtown,Entire home/apt,239,30,0,NaN,NaN,121,351
15042,12001322,NYC Midtown-West Luxury 1BR Apt.,30283594,Kara,Manhattan,Midtown,Entire home/apt,239,30,0,NaN,NaN,121,352
15043,12001638,NYC modern 1 bedroom apt. near Carnegie Hall!,30283594,Kara,Manhattan,Midtown,Entire home/apt,239,30,0,NaN,NaN,121,352
15045,12001854,Luxury 1-Bedroom Midtown West NYC Apartment,30283594,Kara,Manhattan,Midtown,Entire home/apt,239,30,1,2017-11-22,0.05,121,352

In [46]:
nyc_airbnb_dataframe_x.neighbourhood_group.unique()

array(['Manhattan'], dtype=object)